import { ComponentPropsWithoutRef } from "react";

export default function Footer({ className, ...props }: ComponentPropsWithoutRef<"footer">) {
  return (
    <footer className={`mt-2 border-t py-6 text-center text-sm text-gray-500 ${className}`} {...props}>
       © {new Date().getFullYear()} NZLouis | Louis Lu. All rights reserved.
      <div className="mb-2">
      NZLouis&apos; personal project, showcasing AI integration, multi-model routing, and cost-optimized API usage. All quiz content, including questions and AI responses, is generated by AI models and may vary in accuracy.
      </div>
    </footer>
  );
}
